# Messege that has a data related to steering angle from ECU
bool APM_Fd_EN    # Manual/Auto mode transformation request: 0:disable, 1: enable
uint8 Mo_Fd_State
bool APM_Fd_ErrBit_PD
bool APM_Fd_ErrBit_APM
bool APM_Fd_ErrBit_VInfo
bool APM_Fd_ErrBit_SAS
bool APM_Fd_Ovrrd_Ignore
bool APM_Fd_Override
float32 APM_Fd_SteerAngle   # current steering angle
float32 APM_Fd_Steer_Torq # steering torqe value
float32 APM_Fd_Str_out_tq
#int8 APM_Fd_Str_out_tq
uint8 Mo_Fd_AlvCnt





