steering_gear_ratio: 18 #to turn the wheel X radians, we need to turn the steering wheel
wheel_base: 1.53 # wheel_base is the distance b.w. front and rear wheel axis
update_rate: 50
steering_vel: [0.03, 0.7, 0.040841]
# steering_vel: [0.03, 0.7, 0.031416]
#steering_acc: 0.013963
KP: 45
KI: 3
KD: 5
amax: 5
