sudo: required 
dist: trusty 
language: generic 
env:
  matrix:
    - ROS_DISTRO="kinetic" ROS_REPO=ros-shadow-fixed
    - ROS_DISTRO="kinetic" ROS_REPO=ros CATKIN_LINT=pedantic
    - ROS_DISTRO="lunar"   ROS_REPO=ros-shadow-fixed
    - ROS_DISTRO="lunar"   ROS_REPO=ros
    - ROS_DISTRO="kinetic" ROSDEP_SKIP_KEYS=muparser EXPECT_EXIT_CODE=1

install:
  - git clone --depth=1 https://github.com/ros-industrial/industrial_ci.git .ci_config  
script: 
  - .ci_config/travis.sh
