# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mobileye_560_660_msgs/AftermarketLane.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class AftermarketLane(genpy.Message):
  _md5sum = "8a56b7a5f0247252831a59dfc0910af7"
  _type = "mobileye_560_660_msgs/AftermarketLane"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

uint8 LANE_CONFIDENCE_NONE = 0
uint8 LANE_CONFIDENCE_LOW = 1
uint8 LANE_CONFIDENCE_MED = 2
uint8 LANE_CONFIDENCE_HIGH = 3

uint8 LANE_TYPE_DASHED = 0
uint8 LANE_TYPE_SOLID = 1
uint8 LANE_TYPE_NONE = 2
uint8 LANE_TYPE_ROAD_EDGE = 3
uint8 LANE_TYPE_DOUBLE_LANE_MARK = 4
uint8 LANE_TYPE_BOTTS_DOTS = 5
uint8 LANE_TYPE_INVALID = 6

uint8 lane_confidence_left
bool ldw_available_left
uint8 lane_type_left
float32 distance_to_left_lane
uint8 lane_confidence_right
bool ldw_available_right
uint8 lane_type_right
float32 distance_to_right_lane

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  # Pseudo-constants
  LANE_CONFIDENCE_NONE = 0
  LANE_CONFIDENCE_LOW = 1
  LANE_CONFIDENCE_MED = 2
  LANE_CONFIDENCE_HIGH = 3
  LANE_TYPE_DASHED = 0
  LANE_TYPE_SOLID = 1
  LANE_TYPE_NONE = 2
  LANE_TYPE_ROAD_EDGE = 3
  LANE_TYPE_DOUBLE_LANE_MARK = 4
  LANE_TYPE_BOTTS_DOTS = 5
  LANE_TYPE_INVALID = 6

  __slots__ = ['header','lane_confidence_left','ldw_available_left','lane_type_left','distance_to_left_lane','lane_confidence_right','ldw_available_right','lane_type_right','distance_to_right_lane']
  _slot_types = ['std_msgs/Header','uint8','bool','uint8','float32','uint8','bool','uint8','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,lane_confidence_left,ldw_available_left,lane_type_left,distance_to_left_lane,lane_confidence_right,ldw_available_right,lane_type_right,distance_to_right_lane

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AftermarketLane, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.lane_confidence_left is None:
        self.lane_confidence_left = 0
      if self.ldw_available_left is None:
        self.ldw_available_left = False
      if self.lane_type_left is None:
        self.lane_type_left = 0
      if self.distance_to_left_lane is None:
        self.distance_to_left_lane = 0.
      if self.lane_confidence_right is None:
        self.lane_confidence_right = 0
      if self.ldw_available_right is None:
        self.ldw_available_right = False
      if self.lane_type_right is None:
        self.lane_type_right = 0
      if self.distance_to_right_lane is None:
        self.distance_to_right_lane = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.lane_confidence_left = 0
      self.ldw_available_left = False
      self.lane_type_left = 0
      self.distance_to_left_lane = 0.
      self.lane_confidence_right = 0
      self.ldw_available_right = False
      self.lane_type_right = 0
      self.distance_to_right_lane = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3Bf3Bf().pack(_x.lane_confidence_left, _x.ldw_available_left, _x.lane_type_left, _x.distance_to_left_lane, _x.lane_confidence_right, _x.ldw_available_right, _x.lane_type_right, _x.distance_to_right_lane))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 14
      (_x.lane_confidence_left, _x.ldw_available_left, _x.lane_type_left, _x.distance_to_left_lane, _x.lane_confidence_right, _x.ldw_available_right, _x.lane_type_right, _x.distance_to_right_lane,) = _get_struct_3Bf3Bf().unpack(str[start:end])
      self.ldw_available_left = bool(self.ldw_available_left)
      self.ldw_available_right = bool(self.ldw_available_right)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3Bf3Bf().pack(_x.lane_confidence_left, _x.ldw_available_left, _x.lane_type_left, _x.distance_to_left_lane, _x.lane_confidence_right, _x.ldw_available_right, _x.lane_type_right, _x.distance_to_right_lane))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 14
      (_x.lane_confidence_left, _x.ldw_available_left, _x.lane_type_left, _x.distance_to_left_lane, _x.lane_confidence_right, _x.ldw_available_right, _x.lane_type_right, _x.distance_to_right_lane,) = _get_struct_3Bf3Bf().unpack(str[start:end])
      self.ldw_available_left = bool(self.ldw_available_left)
      self.ldw_available_right = bool(self.ldw_available_right)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3Bf3Bf = None
def _get_struct_3Bf3Bf():
    global _struct_3Bf3Bf
    if _struct_3Bf3Bf is None:
        _struct_3Bf3Bf = struct.Struct("<3Bf3Bf")
    return _struct_3Bf3Bf
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
