# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mobileye_560_660_msgs/LkaReferencePoints.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class LkaReferencePoints(genpy.Message):
  _md5sum = "0da833fa4330bb296afc10246a88cb60"
  _type = "mobileye_560_660_msgs/LkaReferencePoints"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

float64 ref_point_1_position
float64 ref_point_1_distance
bool ref_point_1_validity
float64 ref_point_2_position
float64 ref_point_2_distance
bool ref_point_2_validity

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['header','ref_point_1_position','ref_point_1_distance','ref_point_1_validity','ref_point_2_position','ref_point_2_distance','ref_point_2_validity']
  _slot_types = ['std_msgs/Header','float64','float64','bool','float64','float64','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,ref_point_1_position,ref_point_1_distance,ref_point_1_validity,ref_point_2_position,ref_point_2_distance,ref_point_2_validity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LkaReferencePoints, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ref_point_1_position is None:
        self.ref_point_1_position = 0.
      if self.ref_point_1_distance is None:
        self.ref_point_1_distance = 0.
      if self.ref_point_1_validity is None:
        self.ref_point_1_validity = False
      if self.ref_point_2_position is None:
        self.ref_point_2_position = 0.
      if self.ref_point_2_distance is None:
        self.ref_point_2_distance = 0.
      if self.ref_point_2_validity is None:
        self.ref_point_2_validity = False
    else:
      self.header = std_msgs.msg.Header()
      self.ref_point_1_position = 0.
      self.ref_point_1_distance = 0.
      self.ref_point_1_validity = False
      self.ref_point_2_position = 0.
      self.ref_point_2_distance = 0.
      self.ref_point_2_validity = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2dB2dB().pack(_x.ref_point_1_position, _x.ref_point_1_distance, _x.ref_point_1_validity, _x.ref_point_2_position, _x.ref_point_2_distance, _x.ref_point_2_validity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 34
      (_x.ref_point_1_position, _x.ref_point_1_distance, _x.ref_point_1_validity, _x.ref_point_2_position, _x.ref_point_2_distance, _x.ref_point_2_validity,) = _get_struct_2dB2dB().unpack(str[start:end])
      self.ref_point_1_validity = bool(self.ref_point_1_validity)
      self.ref_point_2_validity = bool(self.ref_point_2_validity)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2dB2dB().pack(_x.ref_point_1_position, _x.ref_point_1_distance, _x.ref_point_1_validity, _x.ref_point_2_position, _x.ref_point_2_distance, _x.ref_point_2_validity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 34
      (_x.ref_point_1_position, _x.ref_point_1_distance, _x.ref_point_1_validity, _x.ref_point_2_position, _x.ref_point_2_distance, _x.ref_point_2_validity,) = _get_struct_2dB2dB().unpack(str[start:end])
      self.ref_point_1_validity = bool(self.ref_point_1_validity)
      self.ref_point_2_validity = bool(self.ref_point_2_validity)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_2dB2dB = None
def _get_struct_2dB2dB():
    global _struct_2dB2dB
    if _struct_2dB2dB is None:
        _struct_2dB2dB = struct.Struct("<2dB2dB")
    return _struct_2dB2dB
