// Generated by gencpp from file mobileye_560_660_msgs/Ahbc.msg
// DO NOT EDIT!


#ifndef MOBILEYE_560_660_MSGS_MESSAGE_AHBC_H
#define MOBILEYE_560_660_MSGS_MESSAGE_AHBC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mobileye_560_660_msgs
{
template <class ContainerAllocator>
struct Ahbc_
{
  typedef Ahbc_<ContainerAllocator> Type;

  Ahbc_()
    : header()
    , high_low_beam_decision(0)
    , reasons_for_switch_to_low_beam(0)  {
    }
  Ahbc_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , high_low_beam_decision(0)
    , reasons_for_switch_to_low_beam(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _high_low_beam_decision_type;
  _high_low_beam_decision_type high_low_beam_decision;

   typedef uint16_t _reasons_for_switch_to_low_beam_type;
  _reasons_for_switch_to_low_beam_type reasons_for_switch_to_low_beam;



  enum {
    HIGH_LOW_BEAM_DECISION_NO_RECOMMENDATION = 0u,
    HIGH_LOW_BEAM_DECISION_RECOMMENDATION_OFF = 1u,
    HIGH_LOW_BEAM_DECISION_RECOMMENDATION_ON = 2u,
    HIGH_LOW_BEAM_DECISION_INVALID = 3u,
  };


  typedef boost::shared_ptr< ::mobileye_560_660_msgs::Ahbc_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobileye_560_660_msgs::Ahbc_<ContainerAllocator> const> ConstPtr;

}; // struct Ahbc_

typedef ::mobileye_560_660_msgs::Ahbc_<std::allocator<void> > Ahbc;

typedef boost::shared_ptr< ::mobileye_560_660_msgs::Ahbc > AhbcPtr;
typedef boost::shared_ptr< ::mobileye_560_660_msgs::Ahbc const> AhbcConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobileye_560_660_msgs::Ahbc_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobileye_560_660_msgs::Ahbc_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mobileye_560_660_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'mobileye_560_660_msgs': ['/home/dallddungi/keti_ws/src/mobileye_560_660_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mobileye_560_660_msgs::Ahbc_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobileye_560_660_msgs::Ahbc_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobileye_560_660_msgs::Ahbc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobileye_560_660_msgs::Ahbc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobileye_560_660_msgs::Ahbc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobileye_560_660_msgs::Ahbc_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobileye_560_660_msgs::Ahbc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "475e214fc14bee0ccbbfc2ae7aaea6ec";
  }

  static const char* value(const ::mobileye_560_660_msgs::Ahbc_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x475e214fc14bee0cULL;
  static const uint64_t static_value2 = 0xcbbfc2ae7aaea6ecULL;
};

template<class ContainerAllocator>
struct DataType< ::mobileye_560_660_msgs::Ahbc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobileye_560_660_msgs/Ahbc";
  }

  static const char* value(const ::mobileye_560_660_msgs::Ahbc_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobileye_560_660_msgs::Ahbc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
uint8 HIGH_LOW_BEAM_DECISION_NO_RECOMMENDATION = 0\n\
uint8 HIGH_LOW_BEAM_DECISION_RECOMMENDATION_OFF = 1\n\
uint8 HIGH_LOW_BEAM_DECISION_RECOMMENDATION_ON = 2\n\
uint8 HIGH_LOW_BEAM_DECISION_INVALID = 3\n\
uint8 high_low_beam_decision\n\
\n\
uint16 reasons_for_switch_to_low_beam\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::mobileye_560_660_msgs::Ahbc_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobileye_560_660_msgs::Ahbc_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.high_low_beam_decision);
      stream.next(m.reasons_for_switch_to_low_beam);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ahbc_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobileye_560_660_msgs::Ahbc_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobileye_560_660_msgs::Ahbc_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "high_low_beam_decision: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.high_low_beam_decision);
    s << indent << "reasons_for_switch_to_low_beam: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.reasons_for_switch_to_low_beam);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBILEYE_560_660_MSGS_MESSAGE_AHBC_H
